name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cd /home/runner/work/actualtime/
          rm -rf actualtime/tools actualtime/.git actualtime/.github actualtime/tools actualtime/vendor actualtime/tests actualtime/composer.* actualtime/RoboFile.php
          tar -zcvf actualtime-${{ github.ref_name }}.tgz actualtime

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: actualtime-${{ github.ref_name }}.tgz
          path: /home/runner/work/actualtime/actualtime-${{ github.ref_name }}.tgz

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/work/actualtime/actualtime-${{ github.ref_name }}.tgz
          body: "New release is available"
          name: actualtime ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
